services:
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres 

  postgres:
    image: postgres:16
    ports:
      - 5430:5432
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: app

volumes:
  db:
    driver: local