[config]
default_to_workspace = false

[tasks.set-env-docker.env]
DATABASE_HOST = "postgres"
DATABASE_PORT = "${DATABASE_PORT_INNER}"
DATABASE_URL = "postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"

[tasks.set-env-local.env]
DATABASE_HOST = "localhost"
DATABASE_PORT = "${DATABASE_PORT_OUTER}"
DATABASE_URL = "postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"

[tasks.run]
extend = "set-env-local"
env_files = [".env"]
command = "cargo"
args = ["run"]

[tasks.compose]
extend = "set-env-docker"
env_files = [".env"]
command = "docker"
args = ["compose", "${@}"]

[tasks.compose-up-db]
extend = "set-env-docker"
env_files = [".env"]
command = "docker"
args = ["compose", "up", "-d", "postgres"]

[tasks.compose-down]
extend = "set-env-docker"
env_files = [".env"]
command = "docker"
args = ["compose", "down"]

[tasks.compose-remove]
extend = "set-env-docker"
env_files = [".env"]
command = "docker"
args = ["compose", "down", "-v"]
